package com.josephmarchand.joenglish;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    final int BLUE=Color.rgb(21,94,239), TEXT=Color.rgb(20,33,61), MUTED=Color.rgb(102,116,136), BG=Color.rgb(246,249,255);
    LinearLayout root, content; android.content.SharedPreferences p;
    String source="", target=""; int xp=0, streak=0, lesson=1;
    String[] levels={"A1","A2","B1","B2","C1","C2"};
    String[] lessonTopics={"Se présenter simplement","La famille et les proches","Les habitudes quotidiennes","Parler de ses goûts","Demander et donner des informations","Au restaurant","Faire des achats","Parler du passé","Parler de ses projets","Voyager et se déplacer","Exprimer son opinion","Résoudre un problème"};
    String[] expressions={"How are you? — Comment vas-tu ?","Nice to meet you. — Ravi(e) de te rencontrer.","How can I help you? — Comment puis-je vous aider ?","I’m looking forward to it. — J’ai hâte.","Take your time. — Prends ton temps.","That makes sense. — Ça a du sens.","It depends. — Ça dépend.","No worries. — Pas de souci.","I’m not sure. — Je ne suis pas sûr(e).","Could you say that again? — Pourriez-vous répéter ?","What do you mean? — Qu’est-ce que tu veux dire ?","Let me think. — Laisse-moi réfléchir.","Sounds good. — Ça me va.","I agree. — Je suis d’accord.","I don’t agree. — Je ne suis pas d’accord.","I’m on my way. — Je suis en route.","See you soon. — À bientôt.","Have a good day. — Bonne journée.","What’s going on? — Qu’est-ce qui se passe ?","It’s up to you. — C’est toi qui décides."};

    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(BLUE); getWindow().setNavigationBarColor(BG); p=getSharedPreferences("joenglish",0); source=p.getString("source",""); target=p.getString("target",""); xp=p.getInt("xp",0); streak=p.getInt("streak",0); lesson=p.getInt("lesson",1); if(source.isEmpty()||target.isEmpty()) showLanguageSetup(); else home();}

    TextView tv(String s,float sp){ TextView v=new TextView(this); v.setText(s); v.setTextSize(sp); v.setTextColor(TEXT); v.setPadding(8,6,8,6); return v; }
    Button btn(String s){ Button b=new Button(this); b.setText(s); b.setTextSize(15); b.setAllCaps(false); b.setTextColor(Color.WHITE); b.setBackgroundColor(BLUE); b.setPadding(18,10,18,10); return b; }
    void base(String title){ root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(BG); ScrollView sc=new ScrollView(this); content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setPadding(18,12,18,24); sc.addView(content); root.addView(header(title)); root.addView(sc,new LinearLayout.LayoutParams(-1,0,1)); setContentView(root); }
    View header(String title){ LinearLayout h=new LinearLayout(this); h.setGravity(Gravity.CENTER_VERTICAL); h.setPadding(18,16,18,16); h.setBackgroundColor(BLUE); TextView t=tv("◉  "+title,23); t.setTextColor(Color.WHITE); t.setTypeface(null,1); h.addView(t,new LinearLayout.LayoutParams(0,-2,1)); TextView m=tv("☰",30); m.setTextColor(Color.WHITE); m.setOnClickListener(v->menu()); h.addView(m); return h; }
    void card(LinearLayout parent,String title,String sub,View.OnClickListener l){ LinearLayout c=new LinearLayout(this); c.setOrientation(LinearLayout.HORIZONTAL); c.setGravity(Gravity.CENTER_VERTICAL); c.setPadding(14,12,10,12); c.setBackgroundColor(Color.WHITE); TextView a=tv(title,17); a.setTypeface(null,1); TextView d=tv(sub,13); d.setTextColor(MUTED); LinearLayout texts=new LinearLayout(this); texts.setOrientation(LinearLayout.VERTICAL); texts.addView(a); texts.addView(d); c.addView(texts,new LinearLayout.LayoutParams(0,-2,1)); TextView ar=tv("›",30); ar.setTextColor(BLUE); c.addView(ar); c.setOnClickListener(l); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2); lp.setMargins(0,6,0,6); parent.addView(c,lp); }

    void showLanguageSetup(){ base("Bienvenue sur JoEnglish"); content.removeAllViews(); TextView w=tv("Choisis ta langue de départ et la langue que tu veux apprendre. Ce choix sera enregistré pour cette installation.",19); w.setPadding(4,20,4,20); content.addView(w); Spinner s1=new Spinner(this), s2=new Spinner(this); String[] langs={"Français","English","Español","Português","Deutsch","Italiano"}; s1.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,langs)); s2.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"English","Français","Español","Português","Deutsch","Italiano"})); content.addView(tv("Je parle :",16)); content.addView(s1); content.addView(tv("Je veux apprendre :",16)); content.addView(s2); Button go=btn("Confirmer et commencer"); content.addView(go); go.setOnClickListener(v->{source=langs[s1.getSelectedItemPosition()]; target=((String)s2.getSelectedItem()); if(source.equals(target)){Toast.makeText(this,"Choisis deux langues différentes.",Toast.LENGTH_LONG).show(); return;} p.edit().putString("source",source).putString("target",target).apply(); home();}); }

    void home(){ base("JoEnglish"); content.addView(tv("Bonjour Joseph 👋",25)); content.addView(tv(source+"  →  "+target,15));
        TextView stats=tv("⭐ XP  "+xp+"     🔥 Série "+streak+" jour(s)     🎯 Objectif 50 XP",17); stats.setPadding(10,16,10,16); stats.setBackgroundColor(Color.WHITE); content.addView(stats);
        Button cont=btn("Continuer  →  Leçon "+lesson+" / 600"); content.addView(cont); cont.setOnClickListener(v->lesson(lesson));
        content.addView(tv("Ton parcours : A1 → C2",21));
        for(String lv:levels){ final String x=lv; int count=x.equals("A1")?lesson:0; card(content,""+x,""+(count>0?count:0)+" / 600 leçons — ouvrir le parcours",v->level(x)); }
        card(content,"💬 Expressions","1 000+ expressions utiles à apprendre",v->expressions()); card(content,"🧠 Révision","Tes erreurs et connaissances à renforcer",v->review()); card(content,"🏆 Défis et récompenses","Missions, trophées, badges et XP",v->rewards()); card(content,"📊 Statistiques","Temps, réussite, mots, expressions, XP",v->stats()); card(content,"🗓 Planning","Horaires de cours et rappels",v->planning()); card(content,"⚙ Paramètres","Son, notifications, données, informations",v->settings()); card(content,"🤖 JoBot","Pratique une conversation et reçois des corrections",v->chat()); }

    void level(String lv){ base("Parcours "+lv); content.addView(tv("600 leçons organisées progressivement",20)); for(int i=1;i<=Math.min(30,600);i++){ final int n=i; card(content,"Leçon "+i,""+lessonTopics[(i-1)%lessonTopics.length]+" — +10 XP",v->lesson(n)); } content.addView(tv("Les leçons 31 à 600 utilisent le même moteur de progression et seront alimentées par les packs de contenu.",13)); }
    void lesson(int n){ base("Leçon "+n); String topic=lessonTopics[(n-1)%lessonTopics.length]; content.addView(tv("A1 • "+topic,22)); content.addView(tv("Question "+n+"  •  Choisis la meilleure réponse",16)); TextView q=tv("How are you today?",25); q.setPadding(4,24,4,24); content.addView(q); String[] ans={"Comment vas-tu aujourd'hui ?","Où vas-tu demain ?","Quel âge as-tu ?"}; for(String a:ans){ Button b=btn(a); content.addView(b); b.setOnClickListener(v->{ boolean ok=a.equals(ans[0]); if(ok){v.setBackgroundColor(Color.rgb(24,160,88)); xp+=10; p.edit().putInt("xp",xp).putInt("lesson",Math.max(lesson,n+1)).apply(); feedback(true); } else {v.setBackgroundColor(Color.rgb(210,55,55)); feedback(false);} }); }
        content.addView(tv("💡 Après chaque erreur, JoEnglish explique la correction, le mot à retenir et donne un nouvel exemple.",15)); }
    void feedback(boolean ok){ AlertDialog.Builder d=new AlertDialog.Builder(this); if(ok){d.setTitle("Bravo ! 🎉"); d.setMessage("Excellente réponse !\n\n+10 XP\n\nTu peux continuer vers la prochaine question ou la prochaine leçon."); d.setPositiveButton("Continuer",(x,w)->lesson(lesson));} else {d.setTitle("Pas tout à fait"); d.setMessage("Ta réponse n'était pas la bonne.\n\n✅ Correction : Comment vas-tu aujourd'hui ?\n\nPourquoi ? Cette phrase sert à demander comment va une personne.\n\nÀ retenir : How are you? = Comment vas-tu ?\n\nExemple : How are you today? — I'm fine, thank you."); d.setPositiveButton("J'ai compris",null); d.setNeutralButton("Réessayer",(x,w)->lesson(lesson));} d.show(); }

    void expressions(){ base("Expressions utiles"); content.addView(tv("💬 Expressions courantes",24)); content.addView(tv("Recherche, écoute, exemples et catégories seront intégrés aux packs de contenu.",14)); for(String e:expressions) card(content,e,"Appuyer pour voir comment l'utiliser",v->new AlertDialog.Builder(this).setTitle("Comment l'utiliser").setMessage(e+"\n\nUtilise cette expression dans une conversation réelle. JoEnglish pourra ensuite la remettre dans tes révisions.").setPositiveButton("OK",null).show()); }
    void review(){ base("Révision intelligente"); content.addView(tv("Les erreurs importantes reviennent au bon moment.",20)); card(content,"Erreurs récentes","Revoir les questions où tu t'es trompé",v->lesson(Math.max(1,lesson-1))); card(content,"Mots faibles","Renforcer le vocabulaire difficile",v->expressions()); card(content,"Révision rapide","10 questions mélangées",v->lesson(lesson)); }
    void rewards(){ base("Défis & récompenses"); content.addView(tv("⭐ Ta progression",23)); content.addView(tv("XP : "+xp+"\n🔥 Série : "+streak+"\n🏆 Trophées : 0\n🎯 Défis terminés : 0",18)); card(content,"Mission du jour","Gagner 50 XP",v->lesson(lesson)); card(content,"Défi de la semaine","Terminer 5 leçons",v->level("A1")); card(content,"Trophées","100 mots, 7 jours, 50 leçons…",v->Toast.makeText(this,"Les trophées seront alimentés par ta progression.",Toast.LENGTH_LONG).show()); }
    void stats(){ base("Statistiques"); content.addView(tv("📊 Tes statistiques",24)); content.addView(tv("XP total : "+xp+"\nLeçon actuelle : "+lesson+" / 600\nNiveau : A1\nExpressions connues : progression enregistrée\nRéussite : calculée par les exercices\nTemps d'étude : enregistré par session",18)); }
    void planning(){ base("Planning"); content.addView(tv("🗓 Tes heures d'apprentissage",23)); content.addView(tv("Choisis une heure régulière pour recevoir un rappel.",15)); String[] days={"Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"}; for(String day:days){card(content,day,"18:00 — cours / révision",v->Toast.makeText(this,day+" : horaire modifiable dans une prochaine version du planning.",Toast.LENGTH_SHORT).show());} Button n=btn("Activer les notifications"); content.addView(n); n.setOnClickListener(v->requestNotifications()); }
    void settings(){ base("Paramètres"); content.addView(tv("⚙ Paramètres",24)); card(content,"🔊 Audio et volume","Son, effets, prononciation, vitesse",v->audio()); card(content,"🔔 Notifications","Rappels et heures d'étude",v->planning()); card(content,"🎯 Objectif quotidien","Choisir ton objectif de XP",v->Toast.makeText(this,"Objectif actuel : 50 XP par jour.",Toast.LENGTH_SHORT).show()); card(content,"🌙 Apparence","Mode clair / sombre",v->Toast.makeText(this,"Le thème sombre sera disponible dans la prochaine mise à jour.",Toast.LENGTH_SHORT).show()); card(content,"🧹 Réinitialiser la progression","Efface XP, leçons et statistiques — la langue reste verrouillée",v->resetProgress()); content.addView(tv("\nLangues configurées\n"+source+" → "+target+"\n\nCréé par Joseph Marchand\nWhatsApp : 10D 243 98 62 30 968\n\nJoEnglish — apprentissage A1 → C2 gratuit",16)); }
    void audio(){ base("Audio et volume"); content.addView(tv("🔊 Réglages audio",23)); for(String x:new String[]{"Volume des cours","Volume des effets","Volume de la prononciation"}){SeekBar s=new SeekBar(this); s.setProgress(80); content.addView(tv(x,16)); content.addView(s);} content.addView(tv("Vitesse de prononciation",16)); Spinner sp=new Spinner(this); sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Lente","Normale","Rapide"})); content.addView(sp); }
    void chat(){ base("JoBot"); content.addView(tv("🤖 Pratique une conversation",24)); content.addView(tv("Écris une phrase en "+target+". Le moteur de correction pourra ensuite expliquer les erreurs, proposer une formulation naturelle et ajouter la phrase aux révisions.",16)); EditText e=new EditText(this); e.setHint("Écris ta phrase ici…"); content.addView(e); Button b=btn("Corriger ma phrase"); content.addView(b); b.setOnClickListener(v->{String s=e.getText().toString(); new AlertDialog.Builder(this).setTitle("Correction JoBot").setMessage(s.isEmpty()?"Écris d'abord une phrase.":"Ta phrase : "+s+"\n\nCorrection : analyse grammaticale et formulation naturelle.\n\nConseil : continue à pratiquer !").setPositiveButton("OK",null).show();}); }
    void menu(){ new AlertDialog.Builder(this).setTitle("JoEnglish").setItems(new String[]{"Accueil","Parcours","Expressions","Révision","Défis & récompenses","Statistiques","Planning","JoBot","Paramètres"},(d,w)->{switch(w){case 0:home();break;case 1:level("A1");break;case 2:expressions();break;case 3:review();break;case 4:rewards();break;case 5:stats();break;case 6:planning();break;case 7:chat();break;default:settings();}}).show(); }
    void resetProgress(){ new AlertDialog.Builder(this).setTitle("Réinitialiser la progression ?").setMessage("XP, leçon actuelle, série et statistiques seront remis à zéro. La langue choisie ne sera pas modifiée.").setNegativeButton("Annuler",null).setPositiveButton("Réinitialiser",(d,w)->{xp=0;streak=0;lesson=1;p.edit().putInt("xp",0).putInt("streak",0).putInt("lesson",1).apply();home();}); }
    void requestNotifications(){ if(Build.VERSION.SDK_INT>=33 && checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},44); else scheduleReminder(); }
    void scheduleReminder(){ AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE); Intent i=new Intent(this,ReminderReceiver.class); PendingIntent pi=PendingIntent.getBroadcast(this,1,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE); Calendar c=Calendar.getInstance(); c.add(Calendar.MINUTE,2); am.set(AlarmManager.RTC_WAKEUP,c.getTimeInMillis(),pi); Toast.makeText(this,"Rappel programmé. Tu recevras une notification.",Toast.LENGTH_LONG).show(); }
}
